# Generated by Django 5.0.7 on 2024-07-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сity',
            new_name='City',
        ),
    ]
