# Generated by Django 5.0.7 on 2024-07-20 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weathersearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersearchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
